{% set name = "kcodecs" %}
{% set version = "5.65.0" %}
{% set major_minor = ".".join(version.split(".")[:2]) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://download.kde.org/stable/frameworks/{{ major_minor }}/kcodecs-{{ version }}.tar.xz
  sha256: eca1642a559aad9aed57ea3ad5c7a62a2b20ad13969b6fcba671f5bc7c9782fd

build:
  number: 0
  skip: true  # [not linux]
  run_exports:
    - {{ pin_subpackage('kcodecs', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - extra-cmake-modules
  host:
    - qt
    - gperf

test:
  commands:
    - test -f ${PREFIX}/lib/libKF5Codecs.so

about:
  home: https://api.kde.org/frameworks/kcodecs/html/index.html
  license: GPL-v2
  license_family: GPL
  license_file: COPYING
  summary: 'String encoding library'
  description: |
    KCodecs provide a collection of methods to manipulate strings using various encodings.
    It can automatically determine the charset of a string, translate XML entities,
    validate email addresses, and find encodings by name in a more tolerant way than
    QTextCodec (useful e.g. for data coming from the Internet).
  dev_url: https://cgit.kde.org/kcodecs.git/tree

extra:
  recipe-maintainers:
    - scopatz
